springmvc-master/src/main/java/cn/springmvc/mybatis/entity/activiti/LeaveBill.java
package cn.springmvc.mybatis.entity.activiti;

import java.util.Date;

import cn.springmvc.mybatis.entity.BaseEntity;

/**
 * 请假单
 */
public class LeaveBill implements BaseEntity<Long> {

    private static final long serialVersionUID = -5400999970408251440L;
    private Long id;
    private Integer days;// 请假天数
    private String content;// 请假内容
    private Date leaveDate = new Date();// 请假时间
    private String remark;// 备注
    private String userId;// 请假人

    private Integer state = 0;// 请假单状态 0初始录入,1.开始审批,2为审批完成

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDays() {
        return days;
    }

    public void setDays(Integer days) {
        this.days = days;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getLeaveDate() {
        return leaveDate;
    }

    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }
    
    public String getStateName(){
        if(state==0){
            return "初始录入";
        }else if(state==1){
            return "审核中";
        }else{
            return "审核完成";
        }
    }

}

springmvc-master/src/main/java/cn/springmvc/mybatis/entity/activiti/WorkflowBean.java
package cn.springmvc.mybatis.entity.activiti;

import java.io.File;
import java.io.Serializable;

public class WorkflowBean implements Serializable {

    private static final long serialVersionUID = 6640079924093210089L;
    
    private File file; // 流程定义部署文件
    private String filename;// 流程定义名称

    private Long id;// 申请单ID

    private String deploymentId;// 部署对象ID
    private String imageName; // 资源文件名称
    private String taskId; // 任务ID
    private String outcome; // 连线名称
    private String comment; // 备注

    public File getFile() {
        return file;
    }

    public void setFile(File file) {
        this.file = file;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeploymentId() {
        return deploymentId;
    }

    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId;
    }

    public String getImageName() {
        return imageName;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getOutcome() {
        return outcome;
    }

    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}

springmvc-master/src/main/java/cn/springmvc/mybatis/web/controller/workflow/ActivitiController.java
package cn.springmvc.mybatis.web.controller.workflow;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletResponse;

import org.activiti.engine.repository.Deployment;
import org.activiti.engine.repository.ProcessDefinition;
import org.activiti.engine.task.Comment;
import org.activiti.engine.task.Task;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import cn.springmvc.mybatis.entity.activiti.LeaveBill;
import cn.springmvc.mybatis.entity.activiti.WorkflowBean;
import cn.springmvc.mybatis.entity.auth.User;
import cn.springmvc.mybatis.service.workflow.ActivitiService;
import cn.springmvc.mybatis.web.util.WebUtil;

@Controller
@RequestMapping(value = "activiti")
public class ActivitiController {

    private static final Logger log = LoggerFactory.getLogger(ActivitiController.class);

    @Autowired
    private ActivitiService activitiService;

    /**
     * 请假管理首页显示
     * 
     * @return
     */
    @RequestMapping(value = "home")
    public String home(Model model) {
        log.debug("## 进入请假管理首页");
        // 1：查询所有的请假信息（对应a_leavebill），返回List<LeaveBill>
        List<LeaveBill> list = activitiService.findLeaveBillList();
        // 放置到上下文对象中
        model.addAttribute("list", list);
        return "activiti/home";
    }

    /**
     * 添加请假申请
     * 
     * @return
     */
    @RequestMapping(value = "input")
    public String input(@RequestParam(value = "id", required = false) Long leaveBillId, Model model) {
        log.debug("## 添加请假申请");
        // 1：获取请假单ID
        // 修改
        if (null != leaveBillId) {
            // 2：使用请假单ID，查询请假单信息，
            LeaveBill bill = activitiService.findLeaveBillById(leaveBillId);
            // 3：将请假单信息放置到栈顶，页面使用struts2的标签，支持表单回显
            model.addAttribute("bill", bill);
        } else {
            model.addAttribute("bill", new LeaveBill());
        }
        // 新增
        return "activiti/input";
    }

    /**
     * 保存/更新，请假申请
     * 
     */
    @RequestMapping(value = "save", method = RequestMethod.POST)
    public String save(@ModelAttribute("leaveBill") LeaveBill leaveBill) {
        log.debug("## 保存/更新请假申请");
        // 执行保存
        User user = WebUtil.getUser();
        leaveBill.setUserId(user.getId());
        activitiService.saveLeaveBill(leaveBill);
        return "redirect:/activiti/home";
    }

    /**
     * 删除，请假申请
     * 
     */
    @RequestMapping(value = "delete")
    public String delete(@RequestParam("id") Long leaveBillId, Model model) {
        log.debug("## 删除，请假申请");
        // 1：获取请假单ID
        // 执行删除
        activitiService.deleteLeaveBillById(leaveBillId);
        return "redirect:/activiti/home";
    }

    // ==================以下方法为与工作流相关方法=========================================

    /**
     * 部署管理首页显示
     * 
     * @return
     */
    @RequestMapping(value = "deployHome")
    public String deployHome(Model model) {
        try {
            log.debug("## 部署管理首页显示");
            // 1:查询部署对象信息，对应表（act_re_deployment）
            List<Deployment> depList = activitiService.findDeploymentList();
            // 2:查询流程定义的信息，对应表（act_re_procdef）
            List<ProcessDefinition> pdList = activitiService.findProcessDefinitionList();
            // 放置到上下文对象中
            model.addAttribute("depList", depList);
            model.addAttribute("pdList", pdList);
            return "activiti/workflow";
        } catch (Exception e) {
            log.error("# 进入部署管理首页报错 , error message={}", e.getLocalizedMessage());
            return "/common/404";
        }
    }

    /**
     * 发布流程
     * 
     * @return
     * @throws IOException
     */
    @RequestMapping(value = "newdeploy", method = RequestMethod.POST)
    public String newdeploy(@RequestParam("bpmnZip") MultipartFile bpmnZip, @RequestParam("processDefinitionName") String processDefinitionName, Model model) throws IOException {
        log.debug("## 发布流程");
        // 获取页面传递的值
        // 1：获取页面上传递的zip格式的文件，格式是File类型
        byte bytes[] = bpmnZip.getBytes();
        // 文件名称
        // String filename = bpmnZip.getName();
        // 完成部署
        activitiService.saveNewDeploye(bytes, processDefinitionName);
        return "redirect:/activiti/deployHome";
    }

    /**
     * 删除部署信息
     */
    @RequestMapping(value = "delDeployment")
    public String delDeployment(@RequestParam("deploymentId") String deploymentId) {
        log.debug("## 删除部署信息 ");
        // 1：获取部署对象ID
        // String deploymentId = activitiService.getDeploymentId();
        // 2：使用部署对象ID，删除流程定义
        activitiService.deleteProcessDefinitionByDeploymentId(deploymentId);
        return "redirect:/activiti/deployHome";
    }

    /**
     * 查看流程图
     * 
     * @throws Exception
     */
    @RequestMapping(value = "viewImage")
    public String viewImage(@RequestParam("deploymentId") String deploymentId, @RequestParam("imageName") String imageName, HttpServletResponse response) throws Exception {
        log.debug("## 查看流程图");
        // 1：获取页面传递的部署对象ID和资源图片名称
        // 部署对象ID
        // String deploymentId = activitiService.getDeploymentId();
        // 资源图片名称
        // String imageName = workflowBean.getImageName();
        // 2：获取资源文件表（act_ge_bytearray）中资源图片输入流InputStream
        InputStream in = activitiService.findImageInputStream(deploymentId, imageName);
        // 3：从response对象获取输出流
        OutputStream out = response.getOutputStream();
        // 4：将输入流中的数据读取出来，写到输出流中
        for (int b = -1; (b = in.read()) != -1;) {
            out.write(b);
        }
        out.close();
        in.close();
        // 将图写到页面上，用输出流写
        return null;
    }

    // 启动流程
    @RequestMapping(value = "startProcess")
    public String startProcess(@ModelAttribute("workflowBean") WorkflowBean workflowBean) {
        log.debug("## 启动流程");
        // 更新请假状态，启动流程实例，让启动的流程实例关联业务
        User user = WebUtil.getUser();
        activitiService.saveStartProcess(workflowBean, user);
        return "redirect:/activiti/listTask";
    }

    /**
     * 任务管理首页显示
     * 
     * @return
     */
    @RequestMapping(value = "listTask")
    public String listTask(Model model) {
        log.debug("## 任务管理首页显示");
        // 1：从Session中获取当前用户名
        // 2：使用当前用户名查询正在执行的任务表，获取当前任务的集合List<Task>
        List<Task> list = null;
        if (WebUtil.hasManager()) {
            list = activitiService.findGroupTaskByUserId(WebUtil.getUser().getId());
        } else {
            list = activitiService.findTaskListByName(WebUtil.getUser().getId());
        }
        model.addAttribute("list", list);
        return "activiti/task";
    }

    /**
     * 打开任务表单
     */
    @RequestMapping(value = "viewTaskForm")
    public String viewTaskForm(@RequestParam("taskId") String taskId, Model model) {
        log.debug("## 打开任务表单");
        // 获取任务ID
        // String taskId = workflowBean.getTaskId();
        /** 一：使用任务ID，查找请假单ID，从而获取请假单信息 */
        LeaveBill leaveBill = activitiService.findLeaveBillByTaskId(taskId);
        model.addAttribute("taskId", taskId);
        model.addAttribute("leaveBill", leaveBill);
        // ValueContext.putValueStack(leaveBill);
        /** 二：已知任务ID，查询ProcessDefinitionEntiy对象，从而获取当前任务完成之后的连线名称，并放置到List<String>集合中 */
        List<String> outcomeList = activitiService.findOutComeListByTaskId(taskId);
        model.addAttribute("outcomeList", outcomeList);
        /** 三：查询所有历史审核人的审核信息，帮助当前人完成审核，返回List<Comment> */
        List<Comment> commentList = activitiService.findCommentByTaskId(taskId);
        model.addAttribute("commentList", commentList);
        return "activiti/taskForm";
    }

    // 准备表单数据
    @RequestMapping(value = "audit")
    public String audit(@RequestParam("taskId") String taskId, Model model) {
        log.debug("## 准备表单数据");
        // 获取任务ID
        // String taskId = workflowBean.getTaskId();
        /** 一：使用任务ID，查找请假单ID，从而获取请假单信息 */
        LeaveBill leaveBill = activitiService.findLeaveBillByTaskId(taskId);
        model.addAttribute("leaveBill", leaveBill);
        /** 二：已知任务ID，查询ProcessDefinitionEntiy对象，从而获取当前任务完成之后的连线名称，并放置到List<String>集合中 */
        List<String> outcomeList = activitiService.findOutComeListByTaskId(taskId);
        model.addAttribute("outcomeList", outcomeList);
        /** 三：查询所有历史审核人的审核信息，帮助当前人完成审核，返回List<Comment> */
        List<Comment> commentList = activitiService.findCommentByTaskId(taskId);
        model.addAttribute("commentList", commentList);
        return "taskForm";
    }

    /**
     * 提交任务
     */
    @RequestMapping(value = "submitTask")
    public String submitTask(@ModelAttribute("workflowBean") WorkflowBean workflowBean) {
        log.debug("## 提交任务 ");
        activitiService.saveSubmitTask(workflowBean);
        return "redirect:/activiti/listTask";
    }

    /**
     * 查看当前流程图（查看当前活动节点，并使用红色的框标注）
     */
    @RequestMapping(value = "viewCurrentImage")
    public String viewCurrentImage(@RequestParam("taskId") String taskId, Model model) {
        log.debug("## 查看当前流程图（查看当前活动节点，并使用红色的框标注）");
        // 任务ID
        // String taskId = workflowBean.getTaskId();
        /** 一：查看流程图 */
        // 1：获取任务ID，获取任务对象，使用任务对象获取流程定义ID，查询流程定义对象
        ProcessDefinition pd = activitiService.findProcessDefinitionByTaskId(taskId);
        // workflowAction_viewImage?deploymentId=<s:property value='#deploymentId'/>&imageName=<s:property value='#imageName'/>
        model.addAttribute("deploymentId", pd.getDeploymentId());
        model.addAttribute("imageName", pd.getDiagramResourceName());

springmvc-master/src/main/webapp/WEB-INF/jsp/activiti/home.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>请假申请列表</title>

<link href="<c:url value='/static/jquery/themes/base/jquery-ui.min.css?${version_css}'/>" rel="stylesheet" type="text/css" />

<script src="<c:url value='/static/jquery/ui/jquery-ui.custom.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/jquery.ui.datepicker.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/i18n/jquery.ui.datepicker-zh-CN.min.js?${version_js}'/>" type="text/javascript"></script>
<script type="text/javascript">
  var _ctx = '${ctx}';
  $(function() {
    $("#leaveBillInput").click(function() {
      document.location.href = _ctx + "/activiti/input";
    });
  });
</script>

</head>
<body>

	<form:form class="form-horizontal">
		<div class="form-group">
			<div class="col-sm-2">
				<button class="btn btn-default" type="button" id="leaveBillInput">请假申请</button>
			</div>
		</div>
	</form:form>
	<div class="row">
		<table class="table table-condensed">
			<thead>
				<tr>
					<th>ID</th>
					<th>请假人ID</th>
					<th>请假天数</th>
					<th>请假事由</th>
					<th>请假备注</th>
					<th>请假时间</th>
					<th>请假状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody id="leaveBillBody">
				<c:forEach var="lb" items="${list }" varStatus="cur">
					<tr>
						<td>${lb.id }</td>
						<td>${lb.userId }</td>
						<td>${lb.days }</td>
						<td>${lb.content }</td>
						<td>${lb.remark }</td>
						<td><fmt:formatDate value="${lb.leaveDate}" type="both" /></td>
						<td>${lb.stateName }</td>
						<td><c:choose>
								<c:when test="${lb.state==0 }">
									<a href="${ctx }/activiti/input?id=${lb.id}">修改</a>
									<a href="${ctx }/activiti/delete?id=${lb.id }">删除</a>
									<a href="${ctx }/activiti/startProcess?id=${lb.id }">申请请假</a>
								</c:when>
								<c:when test="${lb.state==1 }">
									<a href="${ctx }/activiti/viewHisComment?id=${lb.id }">查看审核记录</a>
								</c:when>
								<c:otherwise>
									<a href="${ctx }/activiti/delete?id=${lb.id }">删除</a>
									<a href="${ctx }/activiti/viewHisComment?id=${lb.id }">查看审核记录</a>
								</c:otherwise>
							</c:choose></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
	</div>
</body>
</html>

springmvc-master/src/main/webapp/WEB-INF/jsp/activiti/image.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>查看流程图</title>

<link href="<c:url value='/static/jquery/themes/base/jquery-ui.min.css?${version_css}'/>" rel="stylesheet" type="text/css" />
<script src="<c:url value='/static/jquery/ui/jquery-ui.custom.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/jquery.ui.datepicker.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/i18n/jquery.ui.datepicker-zh-CN.min.js?${version_js}'/>" type="text/javascript"></script>
</head>
<body>
	<!-- 1.获取到规则流程图 -->
	<img style="position: absolute; top: 0px; left: 0px;" src="${ctx }/activiti/viewImage?deploymentId=${deploymentId }&imageName=${imageName}">

	<!-- 2.根据当前活动的坐标，动态绘制DIV -->
	<div style="position: absolute;border:1px solid red;top:${acs.y }px;left: ${acs.x }px;width: ${acs.width }px;height:${acs.height }px;   "></div>

</body>
</html>

springmvc-master/src/main/webapp/WEB-INF/jsp/activiti/input.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>请假</title>

<link href="<c:url value='/static/jquery/themes/base/jquery-ui.min.css?${version_css}'/>" rel="stylesheet" type="text/css" />
<script src="<c:url value='/static/jquery/ui/jquery-ui.custom.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/jquery.ui.datepicker.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/i18n/jquery.ui.datepicker-zh-CN.min.js?${version_js}'/>" type="text/javascript"></script>
</head>
<body>
	<form action="${ctx }/activiti/save" id="leaveBill" method="post" class="form-horizontal">
		<input type="hidden" name="id" value="${bill.id }" /> <input type="hidden" name="userId" value="${bill.userId }" />
		<div class="form-group">
			<label for="title" class="col-sm-2 control-label">请假天数：</label>
			<div class="col-sm-3">
				<input type="text" class="form-control" name="days" id="days" value="${bill.days }" />
			</div>
		</div>
		<div class="form-group">
			<label for="content" class="col-sm-2 control-label">请假原因：</label>
			<div class="col-sm-3">
				<textarea class="form-control" name="content" id="content" row="5">${bill.content }</textarea>
			</div>
		</div>
		<div class="form-group">
			<label for="remark" class="col-sm-2 control-label">备注：</label>
			<div class="col-sm-3">
				<textarea class="form-control" name="remark" id="remark" row="5">${bill.remark }</textarea>
			</div>
		</div>
		<div class="form-group input-group-sm">
			<label class="col-sm-2 control-label">&nbsp;</label>
			<div class="col-sm-3">
				<button class="btn btn-default" type="submit" id="saveBtn">提交</button>
			</div>
		</div>
	</form>
</body>
</html>

springmvc-master/src/main/webapp/WEB-INF/jsp/activiti/task.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>个人任务管理列表</title>

<link href="<c:url value='/static/jquery/themes/base/jquery-ui.min.css?${version_css}'/>" rel="stylesheet" type="text/css" />

<script src="<c:url value='/static/jquery/ui/jquery-ui.custom.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/jquery.ui.datepicker.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/i18n/jquery.ui.datepicker-zh-CN.min.js?${version_js}'/>" type="text/javascript"></script>

</head>
<body>


	<div class="panel panel-primary">
		<div class="panel-heading">个人任务管理列表</div>
		<table class="table table-condensed">
			<thead>
				<tr class="success">
					<th>任务ID</th>
					<th>任务名称</th>
					<th>创建时间</th>
					<th>办理人</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody id="leaveBillBody">
				<c:forEach var="dep" items="${list }" varStatus="cur">
					<tr>
						<td>${dep.id }</td>
						<td>${dep.name }</td>
						<td><fmt:formatDate value="${dep.createTime}" type="both" /></td>
						<td>${dep.assignee}</td>
						<td><a href="${ctx}/activiti/viewTaskForm?taskId=${dep.id }">办理任务</a> <a target="_blank" href="${ctx}/activiti/viewCurrentImage?taskId=${dep.id }">查看当前流程图</a></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
	</div>


</body>
</html>

springmvc-master/src/main/webapp/WEB-INF/jsp/activiti/taskForm.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<c:set var="ctx" value="${pageContext.request.contextPath}" />
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<title>任务表单</title>
<link href="<c:url value='/static/jquery/themes/base/jquery-ui.min.css?${version_css}'/>" rel="stylesheet" type="text/css" />

<script src="<c:url value='/static/jquery/ui/jquery-ui.custom.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/jquery.ui.datepicker.min.js?${version_js}'/>" type="text/javascript"></script>
<script src="<c:url value='/static/jquery/ui/i18n/jquery.ui.datepicker-zh-CN.min.js?${version_js}'/>" type="text/javascript"></script>

</head>
<body>


	<div class="panel panel-primary">
		<div class="panel-heading">个人任务管理列表</div>


		<form class="form-horizontal" action="${ctx }/activiti/submitTask" method="post">
			<!-- 请假单ID -->
			<input type="hidden" name="taskId" value="${taskId }" />
			<!-- 任务ID -->
			<input type="hidden" name="id" value="${leaveBill.id }" />
			<div class="form-group">
				<label for="filename" class="col-sm-1 control-label">请假天数:</label>
				<div class="col-sm-3">
					<input class="form-control" name="days" value="${leaveBill.days }" disabled="true" type="text" />
				</div>
			</div>
			<div class="form-group">
				<label for="bpmnZip" class="col-sm-1 control-label">请假原因:</label>
				<div class="col-sm-3">
					<input class="form-control" name="content" value="${leaveBill.content }" disabled="true" type="text" />
				</div>
			</div>
			<div class="form-group">
				<label for="bpmnZip" class="col-sm-1 control-label">请假备注:</label>
				<div class="col-sm-3">
					<input class="form-control" name="remark" value="${leaveBill.remark }" disabled="true" type="text" />
				</div>
			</div>
			<div class="form-group">
				<label for="bpmnZip" class="col-sm-1 control-label">批注:</label>
				<div class="col-sm-3">
					<input class="form-control" name="comment" type="text" />
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-1 col-sm-3">
					<c:if test="${(outcomeList)!= null && fn:length(outcomeList) > 0}">
						<c:forEach items="${outcomeList }" var="outcome">
							<button type="submit" class="btn btn-default">${outcome }</button>
						</c:forEach>
					</c:if>


				</div>
			</div>
		</form>
	</div>

	<c:choose>
		<c:when test="${(commentList)!= null && fn:length(commentList) > 0}">
			<div class="panel panel-primary">
				<div class="panel-heading">显示请假申请的批注信息</div>
				<table class="table table-condensed">
					<thead>
						<tr>
							<td>时间</td>
							<!-- <td>批注人</td> -->
							<td>批注信息</td>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${commentList }" var="c">
							<td><fmt:formatDate value="${c.time }" type="both" /></td>
							<%-- <td>${c.usreId }</td> --%>
							<td>${c.fullMessage }</td>
						</c:forEach>
					</tbody>
				</table>
			</div>
		</c:when>
		<c:otherwise>
			<div class="well">
				<p class="text-success">暂时没有批注信息</p>
			</div>
		</c:otherwise>
	</c:choose>

</body>
</html>